# Generated by Django 5.2.8 on 2025-12-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areas_of_expertise',
            field=models.TextField(blank=True, help_text='Your key areas of expertise'),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='current_role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='deal_size_preference',
            field=models.CharField(blank=True, help_text='Preferred deal size range', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='geographic_focus',
            field=models.CharField(blank=True, help_text='Geographic regions of focus', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='industry_focus',
            field=models.TextField(blank=True, help_text='Industries you focus on'),
        ),
        migrations.AddField(
            model_name='user',
            name='investment_experience',
            field=models.CharField(blank=True, help_text='Years of investment experience', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='value_proposition',
            field=models.TextField(blank=True, help_text='What unique value do you bring?'),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
