# Generated by Django 5.2.8 on 2025-12-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_aiservice_aiagent_aiinteractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiservice',
            name='description',
            field=models.TextField(blank=True, help_text='Description of this AI service'),
        ),
    ]
