# Generated by Django 5.2.8 on 2025-12-16 10:02

from django.db import migrations, models


def copy_json_data(apps, schema_editor):
    """Copy data from temporary JSON field to the final field"""
    User = apps.get_model('users', 'User')
    
    for user in User.objects.all():
        if hasattr(user, 'education_json') and user.education_json:
            user.education = user.education_json
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_convert_education_to_json'),
    ]

    operations = [
        # Remove the old TextField and rename the JSON field
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        
        migrations.RenameField(
            model_name='user',
            old_name='education_json',
            new_name='education',
        ),
        
        # Copy data over
        migrations.RunPython(copy_json_data, migrations.RunPython.noop),
    ]
