# Generated by Django 5.2.8 on 2026-01-16 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='signed_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to='users.signed_links'),
        ),
    ]
