# Generated by Django 5.2.8 on 2026-01-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_fix_url_fields_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.TextField(blank=True, help_text='Notable achievements and awards', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='areas_of_expertise',
            field=models.TextField(blank=True, help_text='Your key areas of expertise', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Professional bio/summary', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='certifications',
            field=models.TextField(blank=True, help_text='Professional certifications', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='deal_size_preference',
            field=models.CharField(blank=True, help_text='Preferred deal size range', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='existing_buyer_profile',
            field=models.TextField(blank=True, help_text='Content extracted from uploaded buyer profile', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='geographic_focus',
            field=models.CharField(blank=True, help_text='Geographic regions of focus', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='industry_focus',
            field=models.TextField(blank=True, help_text='Industries you focus on', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='investment_experience',
            field=models.CharField(blank=True, help_text='Years of investment experience', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.CharField(blank=True, help_text='Languages spoken', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume_upload',
            field=models.TextField(blank=True, help_text='Content extracted from uploaded resume', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, help_text='Key skills and competencies', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='value_proposition',
            field=models.TextField(blank=True, help_text='What unique value do you bring?', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='years_experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
