# Generated by Django 5.2.8 on 2026-01-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
