# Generated by Django 5.2.8 on 2026-02-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acquisition_target',
            field=models.TextField(blank=True, help_text='What the user is looking to buy; prefer explicit buyer profile content if uploaded', null=True),
        ),
    ]
