# Generated by Django 5.2.8 on 2026-03-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='helper_text',
            field=models.CharField(blank=True, default='', help_text='Short help information'),
        ),
    ]
