version: 0.0
os: linux

files:
  - source: /src
    destination: /app/src
  - source: /requirements.txt
    destination: /app
  - source: /prod.yml
    destination: /app
  - source: /compose
    destination: /app/compose
  - source: /deploy
    destination: /app/deploy

permissions:
  - object: /app
    owner: django
    group: django
    type:
      - directory
      - file

hooks:
  AfterInstall:
    - location: deploy/scripts/after_install.sh
      timeout: 120
      runas: root

  ApplicationStart:
    - location: deploy/scripts/start_app.sh
      timeout: 60
      runas: root

