# Generated by Django 5.2.8 on 2025-12-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_areas_of_expertise_user_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.TextField(blank=True, help_text='Notable achievements and awards'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Professional bio/summary'),
        ),
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.TextField(blank=True, help_text='Professional certifications'),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.TextField(blank=True, help_text='Educational background'),
        ),
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.CharField(blank=True, help_text='Languages spoken', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, help_text='Key skills and competencies'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Personal or company website'),
        ),
    ]
