# Generated by Django 5.2.8 on 2025-12-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_achievements_user_bio_user_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='existing_buyer_profile',
            field=models.TextField(blank=True, help_text='Content extracted from uploaded buyer profile'),
        ),
        migrations.AddField(
            model_name='user',
            name='resume_upload',
            field=models.TextField(blank=True, help_text='Content extracted from uploaded resume'),
        ),
    ]
