# Generated by Django 5.2.8 on 2025-12-09 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_existing_buyer_profile_user_resume_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the AI service', max_length=100)),
                ('service_type', models.CharField(choices=[('openai', 'OpenAI (GPT)'), ('anthropic', 'Anthropic (Claude)'), ('google', 'Google (Gemini)'), ('azure', 'Azure OpenAI'), ('local', 'Local Model'), ('custom', 'Custom API')], help_text='Type of AI service', max_length=20)),
                ('api_endpoint', models.URLField(blank=True, help_text='API endpoint URL (if custom)')),
                ('model_name', models.CharField(help_text='Model name (e.g., gpt-4, claude-3-sonnet)', max_length=100)),
                ('api_key_name', models.CharField(default='OPENAI_API_KEY', help_text='Environment variable name for API key', max_length=50)),
                ('max_tokens', models.IntegerField(default=4000, help_text='Maximum tokens for responses')),
                ('temperature', models.FloatField(default=0.1, help_text='Temperature for response randomness (0.0-1.0)')),
                ('input_cost_per_1k_tokens', models.DecimalField(decimal_places=6, default=0.0, help_text='Cost per 1K input tokens in USD', max_digits=10)),
                ('output_cost_per_1k_tokens', models.DecimalField(decimal_places=6, default=0.0, help_text='Cost per 1K output tokens in USD', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Use this as the default service')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Service',
                'verbose_name_plural': 'AI Services',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the AI agent', max_length=100)),
                ('agent_type', models.CharField(choices=[('profile_extraction', 'Profile Extraction'), ('content_generation', 'Content Generation'), ('data_analysis', 'Data Analysis'), ('chat_assistant', 'Chat Assistant'), ('custom', 'Custom Agent')], help_text='Type of agent', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Description of what this agent does')),
                ('system_prompt', models.TextField(help_text="System prompt that defines the agent's role and behavior")),
                ('user_prompt_template', models.TextField(help_text='Template for user prompts (can include variables like {text})')),
                ('custom_temperature', models.FloatField(blank=True, help_text='Override temperature for this agent', null=True)),
                ('custom_max_tokens', models.IntegerField(blank=True, help_text='Override max tokens for this agent', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_service', models.ForeignKey(help_text='Which AI service to use', on_delete=django.db.models.deletion.CASCADE, to='users.aiservice')),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
                'ordering': ['agent_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIInteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, help_text='Session identifier for grouping related requests', max_length=100)),
                ('input_text', models.TextField(help_text='Input text sent to AI')),
                ('system_prompt_used', models.TextField(help_text='System prompt that was used')),
                ('user_prompt_used', models.TextField(help_text='User prompt that was sent')),
                ('temperature_used', models.FloatField(help_text='Temperature setting used')),
                ('max_tokens_used', models.IntegerField(help_text='Max tokens setting used')),
                ('model_used', models.CharField(help_text='Model name that was used', max_length=100)),
                ('response_text', models.TextField(blank=True, help_text='Raw response from AI')),
                ('parsed_response', models.JSONField(default=dict, help_text='Parsed/structured response data')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed')),
                ('request_timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_timestamp', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Time taken for the request', null=True)),
                ('input_tokens', models.IntegerField(blank=True, help_text='Number of input tokens used', null=True)),
                ('output_tokens', models.IntegerField(blank=True, help_text='Number of output tokens generated', null=True)),
                ('total_tokens', models.IntegerField(blank=True, help_text='Total tokens used', null=True)),
                ('input_cost', models.DecimalField(blank=True, decimal_places=6, help_text='Cost of input tokens', max_digits=10, null=True)),
                ('output_cost', models.DecimalField(blank=True, decimal_places=6, help_text='Cost of output tokens', max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=6, help_text='Total cost of the request', max_digits=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('additional_metadata', models.JSONField(default=dict, help_text='Any additional metadata')),
                ('agent', models.ForeignKey(help_text='Which agent was used', on_delete=django.db.models.deletion.CASCADE, to='users.aiagent')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the request', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Interaction Log',
                'verbose_name_plural': 'AI Interaction Logs',
                'ordering': ['-request_timestamp'],
                'indexes': [models.Index(fields=['agent', 'request_timestamp'], name='users_aiint_agent_i_0ac791_idx'), models.Index(fields=['user', 'request_timestamp'], name='users_aiint_user_id_c1ce91_idx'), models.Index(fields=['status', 'request_timestamp'], name='users_aiint_status_1eff25_idx')],
            },
        ),
    ]
