# Generated by Django 5.2.8 on 2025-12-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_aiservice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_data',
            field=models.JSONField(blank=True, help_text='Structured LinkedIn profile data', null=True),
        ),
    ]
