# Generated by Django 5.2.8 on 2025-12-16 10:02

from django.db import migrations, models


def add_temp_fields(apps, schema_editor):
    """Add temporary fields to store JSON data"""
    pass  # Django will handle adding the fields


def convert_education_data(apps, schema_editor):
    """Convert existing education text data to JSON format"""
    User = apps.get_model('users', 'User')
    
    for user in User.objects.all():
        if hasattr(user, 'education') and user.education and isinstance(user.education, str) and user.education.strip():
            # Convert text education to JSON structure
            education_list = []
            education_text = user.education.strip()
            
            if education_text:
                # Simple parsing - create basic structure from text
                lines = education_text.replace(';', '\n').replace('|', '\n').split('\n')
                
                for line in lines:
                    line = line.strip()
                    if line:
                        education_entry = {
                            'description': line,
                            'school': None,
                            'degree': None,
                            'field': None,
                            'years': None
                        }
                        
                        # Try to extract basic info
                        if ',' in line:
                            parts = [p.strip() for p in line.split(',')]
                            if len(parts) >= 2:
                                education_entry['degree'] = parts[0]
                                education_entry['school'] = parts[1]
                        
                        education_list.append(education_entry)
                
                user.education_json = education_list if education_list else None
                user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_linkedin_data'),
    ]

    operations = [
        # Add temporary JSON fields
        migrations.AddField(
            model_name='user',
            name='education_json',
            field=models.JSONField(blank=True, null=True, help_text='Temporary field for education conversion'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_experience',
            field=models.JSONField(blank=True, null=True, help_text='Professional experience as chronological list'),
        ),
        
        # Convert existing data
        migrations.RunPython(convert_education_data, migrations.RunPython.noop),
    ]
