# Generated by Django 5.2.8 on 2025-12-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_finalize_education_conversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.JSONField(blank=True, help_text='Educational background as list of institutions/degrees', null=True),
        ),
    ]
