# Generated by Django 5.2.8 on 2025-12-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.JSONField(blank=True, default=list, help_text="List of education entries: [{'school': str, 'degree': str, 'field': str, 'years': str, 'description': str}, ...]"),
        ),
        migrations.AlterField(
            model_name='user',
            name='professional_experience',
            field=models.JSONField(blank=True, default=list, help_text="List of work experience: [{'company': str, 'title': str, 'duration': str, 'description': str, 'achievements': str}, ...]"),
        ),
    ]
