# Generated by Django 5.2.8 on 2025-12-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_education_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(help_text='Unique identifier for the question', max_length=100, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='The question text displayed to users')),
                ('question_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('select', 'Select Dropdown')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False, help_text='Whether this question must be answered')),
                ('placeholder', models.CharField(blank=True, help_text='Placeholder text for input fields', max_length=500)),
                ('options', models.JSONField(blank=True, help_text='Options for select type questions (list of strings)', null=True)),
                ('order', models.PositiveIntegerField(help_text='Display order of the question')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
