# Generated by Django 5.2.8 on 2026-01-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deal_size_preference',
            field=models.CharField(blank=True, help_text='Preferred deal size range', max_length=200),
        ),
    ]
