# Generated by Django 5.2.8 on 2026-01-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
