# Generated by Django 5.2.8 on 2026-02-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_user_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
