# Generated by Django 5.2.8 on 2026-02-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
