# Generated by Django 5.2.8 on 2026-02-19 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_acquisition_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='component',
            field=models.CharField(blank=True, help_text='Optional frontend component name/identifier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='Additional JSON metadata for custom question components'),
        ),
        migrations.AddField(
            model_name='question',
            name='validation',
            field=models.JSONField(blank=True, default=dict, help_text='Validation rules and metadata for this question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='Options for select/radio/checkbox questions (list)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Text Area'), ('select', 'Select Dropdown'), ('radio', 'Radio / Single Select'), ('checkbox', 'Single Checkbox'), ('multiselect', 'Multi Select'), ('checkbox_group', 'Checkbox Group / Multi Select'), ('custom', 'Custom (frontend-managed)'), ('composite', 'Composite / Group of sub-questions')], default='text', help_text='Type of question to control frontend rendering', max_length=30),
        ),
    ]
