# Generated by Django 5.2.8 on 2026-02-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_update_text_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='examples',
            field=models.JSONField(blank=True, default=list, help_text='Short example values to display for this question'),
        ),
    ]
