# Generated by Django 5.2.8 on 2026-02-22 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_populate_q3_metadata'),
        ('users', '0036_add_question_page_and_page2_questions'),
    ]

    operations = [
    ]
