# Generated by Django 5.2.8 on 2026-02-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_merge_20260222_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='investment_experience',
            field=models.CharField(blank=True, help_text='Years of investment experience', max_length=500, null=True),
        ),
    ]
