# Generated by Django 5.2.8 on 2026-02-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_alter_user_investment_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_statement',
            field=models.TextField(blank=True, help_text='Short target statement: 1 sentence with business type, size, geography', null=True),
        ),
    ]
