# Generated by Django 5.2.8 on 2026-03-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_user_target_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_create_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when api_token was first created', null=True),
        ),
    ]
