services:
  django:
    build:
      context: .
      dockerfile: compose/Dockerfile
    working_dir: /app
    command: >
      sh -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn searcher_api.wsgi:application --bind 0.0.0.0:${APP_PORT:-8000} --workers 3 --timeout 120"
    restart: unless-stopped
    ports:
      - "80:${APP_PORT:-8000}"
    volumes:
      - ./src/staticfiles:/app/staticfiles
      - ./src/media:/app/media
    env_file:
      - .env.production
      - .env.db
    environment:
      DJANGO_SETTINGS_MODULE: searcher_api.settings

