#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

echo "running collect static... "
python manage.py collectstatic --noinput &&
python manage.py migrate &&
gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120

