#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

# python /wait_for_postgres.py &&
python manage.py collectstatic --noinput
#python manage.py migrate &&

# Export container env for cron jobs
# env | sed 's/"/\\"/g; s/=/="/; s/$/"/' > /etc/container_env

# Start cron daemon in background and log to stdout
# crond -b -l 8 -L /proc/1/fd/1

python manage.py runserver 0.0.0.0:8000
